Name:           ros-hydro-reconfigure-inflation
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS reconfigure_inflation package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/strands-project/strands_apps
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-actionlib-msgs
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-move-base-msgs
Requires:       ros-hydro-rospy
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-actionlib-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-move-base-msgs
BuildRequires:  ros-hydro-rospy

%description
The reconfigure inflation package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sat Oct 18 2014 Nils Bore <nilsbore@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Mon Oct 13 2014 Nils Bore <nilsbore@gmail.com> - 0.0.2-0
- Autogenerated by Bloom

* Tue Sep 23 2014 Nils Bore <nilsbore@gmail.com> - 0.0.1-0
- Autogenerated by Bloom

